name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  flutter_svg: ^2.0.16
  crypto: ^3.0.6
  encrypt: ^5.0.0
  pointycastle: ^3.6.2
  asn1lib: ^1.5.8
  universal_html: ^2.2.4
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/undraw_sign-up_z2ku.svg